# Nombre de la aplicacion
spring.application.name=beautylab

#conexion a la base de datos MongoDB
spring.mongodb.uri=mongodb://localhost:27017/BeautyLab

# Configuracion del puerto del servidor
server.port=8080

# Log de Spring - Nivel INFO para ver solo lo importante
logging.level.org.springframework=INFO

#variable de entorno jwt
app.jwt.secret=${JWT_SECRET}
